theme: jekyll-theme-cayman
title: MSABrowser
show_downloads: true
github:
  repository_url: https://github.com/msabrowser/msabrowser/archive/master.zip
  zip_url: https://github.com/msabrowser/msabrowser/archive/master.zip
