theme: jekyll-theme-cayman
title: MSABrowser
show_downloads: true
github:
  zip_url: https://github.com/msabrowser/MSABrowser.github.io/archive/master.zip
  another_url: https://github.com/msabrowser/MSABrowser.github.io
